// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ploskirev/go-rocket/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: _a0, uuid
func (_m *PartRepository) GetPart(_a0 context.Context, uuid string) (*model.Part, error) {
	ret := _m.Called(_a0, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(_a0, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(_a0, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - _a0 context.Context
//   - uuid string
func (_e *PartRepository_Expecter) GetPart(_a0 interface{}, uuid interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", _a0, uuid)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(_a0 context.Context, uuid string)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(_a0 *model.Part, _a1 error) *PartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: _a0, filters
func (_m *PartRepository) ListParts(_a0 context.Context, filters *model.Filters) []*model.Part {
	ret := _m.Called(_a0, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []*model.Part); ok {
		r0 = rf(_a0, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	return r0
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - _a0 context.Context
//   - filters *model.Filters
func (_e *PartRepository_Expecter) ListParts(_a0 interface{}, filters interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", _a0, filters)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(_a0 context.Context, filters *model.Filters)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(_a0 []*model.Part) *PartRepository_ListParts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(context.Context, *model.Filters) []*model.Part) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
