// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ploskirev/go-rocket/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, UUID
func (_m *PartService) GetPart(ctx context.Context, UUID string) (*model.Part, error) {
	ret := _m.Called(ctx, UUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, UUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, UUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, UUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - UUID string
func (_e *PartService_Expecter) GetPart(ctx interface{}, UUID interface{}) *PartService_GetPart_Call {
	return &PartService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, UUID)}
}

func (_c *PartService_GetPart_Call) Run(run func(ctx context.Context, UUID string)) *PartService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartService_GetPart_Call) Return(_a0 *model.Part, _a1 error) *PartService_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartService_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *PartService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filters
func (_m *PartService) ListParts(ctx context.Context, filters *model.Filters) ([]*model.Part, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) ([]*model.Part, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filters) []*model.Part); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filters
func (_e *PartService_Expecter) ListParts(ctx interface{}, filters interface{}) *PartService_ListParts_Call {
	return &PartService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filters)}
}

func (_c *PartService_ListParts_Call) Run(run func(ctx context.Context, filters *model.Filters)) *PartService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filters))
	})
	return _c
}

func (_c *PartService_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *PartService_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartService_ListParts_Call) RunAndReturn(run func(context.Context, *model.Filters) ([]*model.Part, error)) *PartService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
